config/routes.rb
WeiboMarketingPlatform::Application.routes.draw do
  get "competitor/index"

  get "follow/index"

  root :to => 'dashboard#index'
  
  get '/admin' => "status#index"
  match '/admin/login' => "members#login"
  get '/admin/logout' => "members#logout"

  resources :members
  get 'members/:id/delete' => 'members#delete'

  get "dashboard" => 'dashboard#index'
  get "get_count_of_all_users" => 'dashboard#get_count_of_all_users'

  get 'login' => "dashboard#login"
  get 'logout' => "dashboard#logout"
  get 'auth' => "dashboard#auth"

  get 'follow' => 'follow#index'
  get 'follow/follow' => 'follow#follow'
  get 'follow/unfollow' => 'follow#unfollow'

  get 'lbs' => 'lbs#index'
  post 'lbs/export' => 'lbs#export'

  get 'weibo/rate_limit' => 'weibo#rate_limit'
  get 'weibo/uid' => 'weibo#get_uid_by_name'
  get 'weibo/ajax_get_friends' => 'weibo#ajax_get_friends'
  get 'weibo/ajax_get_followers' => 'weibo#ajax_get_followers'
  get 'weibo/ajax_get_friends_latest_weibo' => 'weibo#ajax_get_friends_latest_weibo'
  get 'weibo/ajax_get_single_user_weibo' => 'weibo#ajax_get_single_user_weibo'
  get 'weibo/ajax_comment_weibo' => 'weibo#ajax_comment_weibo'
  get 'weibo/ajax_repost_weibo' => 'weibo#ajax_repost_weibo'
  get 'weibo/ajax_nearby_timeline' => 'weibo#ajax_nearby_timeline'
  get 'weibo/ajax_nearby_users' => 'weibo#ajax_nearby_users'
  get 'weibo/statuses' => 'weibo#statuses'
  
  get 'competitor' => 'competitor#index'
  get 'competitor/interactive_users_of_one_account' => 'weibo#interactive_users_of_one_account'
  get 'competitor/rt_interactive_users_of_one_account' => 'competitor#rt_interactive_users_of_one_account'
  get 'competitor/interactive_users_of_one_status' => 'weibo#interactive_users_of_one_status'

  match 'repost/setting'

  get 'interactive' => 'interactive#index'

  get 'push' => 'push#index'

  get 'service/advanced'

  get "distribution" => 'distribution#index'
  get "distribution/get_count_of_users_groupby_province" => 'distribution#get_count_of_users_groupby_province'
  get "distribution/get_count_of_users_groupby_v" => 'distribution#get_count_of_users_groupby_v'
  get "distribution/get_count_of_users_groupby_gender" => 'distribution#get_count_of_users_groupby_gender'
  get "distribution/get_count_of_users_groupby_age" => 'distribution#get_count_of_users_groupby_age'

  get "status" => 'status#index'
  get "status/get_total_user_status_of_a_province" => 'status#get_total_user_status_of_a_province'
  get "status/get_daily_user_status_of_a_province" => 'status#get_daily_user_status_of_a_province'
  get "status/get_crawler_progress" => 'status#get_crawler_progress'
  get "status/get_web_cook_status_of_a_province" => 'status#get_web_cook_status_of_a_province'
  get "status/get_mobile_cook_status_of_a_province" => 'status#get_mobile_cook_status_of_a_province'
  get "status/get_disk_status" => 'status#get_disk_status'
  get "status/get_cpu_status" => 'status#get_cpu_status'
  get "status/get_rake_status" => 'status#get_rake_status'
  get "status/get_timeline_crawler_status" => 'status#get_timeline_crawler_status'
  get "status/get_repost_robot_status" => 'status#get_repost_robot_status'
  
  
  get "search" => "search#index"
  get "search/result" => "search#result"
  get "search/statistics" => "search#statistics"
  get "search/export" => "search#export"
  get "search/get_count_of_users_groupby_province" => 'search#get_count_of_users_groupby_province'
  get "search/get_count_of_users_groupby_v" => 'search#get_count_of_users_groupby_v'
  get "search/get_count_of_users_groupby_gender" => 'search#get_count_of_users_groupby_gender'
  get "search/get_count_of_users_groupby_age" => 'search#get_count_of_users_groupby_age'  
  get "search/get_export_percent" => "search#get_export_percent"
  get "search/export_dialog" => "search#export_dialog"
  get "search/generate_csv" => "search#generate_csv"

  resources :cooks
  get 'cooks/:id/delete' => 'cooks#delete'
  get 'users/export'
  get 'cities' =>  'city#index'
  resources :users  # The priority is based upon order of creation:

end

app/models/cook.rb
class Cook < ActiveRecord::Base
  attr_accessible :content, :expired, :page_type, :username, :passwd, :frequent, :forbidden, :owner, :remark#, :uid, :forbidden
end

app/controllers/cooks_controller.rb
# -*- coding: utf-8 -*-
class CooksController < ApplicationController
  layout "admin"
  before_filter :admin_authorize
  # GET /cooks
  # GET /cooks.json
  def index
    @province = params[:province]
    Cook.switch_connection_to(params[:province]) if !params[:province].nil?
    if params[:owner].nil?
      if params[:type].nil?
        @cooks = Cook.order("page_type desc, owner desc, expired desc, frequent desc")
      else
        @cooks = Cook.where("page_type = ? and frequent = ?", params[:type], false).order("owner desc, expired desc, frequent desc")
      end
    else
      if params[:type].nil?
        @cooks = Cook.where("owner = ?", params[:owner]).order("page_type desc, owner desc, expired desc, frequent desc")
      else
        @cooks = Cook.where("owner = ? and page_type = ? and frequent = ?", params[:owner], params[:type], false).order("page_type desc, owner desc, expired desc, frequent desc")
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cooks }
    end
  end

  # GET /cooks/1
  # GET /cooks/1.json
  def show
    @cook = Cook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cook }
    end
  end

  # GET /cooks/new
  # GET /cooks/new.json
  def new
    @cook = Cook.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cook }
    end
  end

  # GET /cooks/1/edit
  def edit
    @cook = Cook.find(params[:id])
  end

  # POST /cooks
  # POST /cooks.json
  def create
    @cook = Cook.new(params[:cook])

    respond_to do |format|
      if @cook.save
        format.html { redirect_to @cook, notice: '新建成功' }
        format.json { render json: @cook, status: :created, location: @cook }
      else
        format.html { render action: "new" }
        format.json { render json: @cook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cooks/1
  # PUT /cooks/1.json
  def update
    @cook = Cook.find(params[:id])

    respond_to do |format|
      if @cook.update_attributes(params[:cook])
        format.html { redirect_to cooks_url}
        # format.html { redirect_to @cook, notice: '更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cooks/1
  # DELETE /cooks/1.json
  #def destroy
  #  @cook = Cook.find(params[:id])
  #  @cook.destroy

  #  respond_to do |format|
  #    format.html { redirect_to cooks_url }
  #    format.json { head :no_content }
  #  end
  #end

  #/cooks/1/delete
  def delete
    @cook = Cook.find(params[:id])
    @cook.destroy

    respond_to do |format|
      format.html { redirect_to cooks_url }
      format.json { head :no_content }
    end

  end

end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/views/cooks/_form.html.erb
<style>
  textarea {width:760px;}
  input[type=text] {
    width:760px;
  }
  .control-label {
    float: left;
    width: 100px;
    padding-top: 5px;
    text-align: right;
  }
  .controls {
    margin-left: 120px;
    margin-bottom: 18px;
  }
</style>
<div class="well">
<%= form_for(@cook, :class=>"form-horizontal") do |f| %>
  <% if @cook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cook.errors.count, "error") %> prohibited this cook from being saved:</h2>

      <ul>
      <% @cook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label">Cookie</label>
    <div class="controls">
      <%= f.text_area :content, :cols => "100", :rows => "12" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">已过期</label>
    <div class="controls">
      <%= f.check_box :expired %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">访问频繁</label>
    <div class="controls">
      <%= f.check_box :frequent %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">拥有者</label>
    <div class="controls">
      <%= f.text_field :owner %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">帐号</label>
    <div class="controls">
      <%= f.text_field :username %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">密码</label>
    <div class="controls">
      <%= f.text_field :passwd %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Cookie类型</label>
    <div class="controls">
      <%= f.text_field :page_type %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">备注</label>
    <div class="controls">
      <%= f.text_area :remark, :cols => "100", :rows => "2" %>
    </div>
  </div>
  <div class="actions" style="text-align:center;">
    <input type="submit" class="btn-large btn-primary" >
  </div>
<% end %>
</div>

app/views/cooks/edit.html.erb
<h1>修改Cookie</h1>

<%= render 'form' %>

<%= link_to 'Show', @cook %> |
<%= link_to 'Back', cooks_path %>

app/views/cooks/index.html.erb
<h1>Cookie列表</h1>
<form class="form-inline" action="/cooks" method="get">
    <select name="province">
      <option value="shanghai" <% if @province=="shanghai"%>selected="selected"<% end %>>上海</option>
      <option value="beijing" <% if @province=="beijing"%>selected="selected"<% end %>>北京</option>
      <option value="guangdong"<% if @province=="guangdong"%>selected="selected"<% end %>>广东</option>
      <option value="zhejiang"<% if @province=="zhejiang"%>selected="selected"<% end %>>浙江</option>
      <option value="jiangsu"<% if @province=="jiangsu"%>selected="selected"<% end %>>江苏</option>
    </select>
    <input type="hidden" name="type" value="web" />
    <button type="submit">切换</button>
</form>

<%= link_to '新建', new_cook_path %>

<table class="table table-condensed">
  <tr>
    <th>序号</th>
    <th style="width:80px;">页面类型</th>
    <th>是否过期</th>
    <th>是否频繁访问</th>
    <th>用户名</th>
    <th>密码</th>
    <th style="width:100px;">拥有者</th>
    <th>Cookie内容</th>
    <th>备注</th>
    <th>更新时间</th>
    <th style="width:40px;"></th>
    <th style="width:40px;"></th>
    <th style="width:40px;"></th>
  </tr>

<% @cooks.each_with_index do |cook,index| %>
  <tr>
    <td><%= index+1 %></td>
    <td><%= cook.page_type %></td>
    <td><% if cook.expired %>是<% else  %>否<% end %></td>
    <td><% if cook.frequent %>是<% else  %>否<% end %></td>
    <td><%= cook.username %></td>
    <td><%= cook.passwd %></td>
    <td><%= cook.owner %></td>
    <td>
      <% if cook.content && cook.content.length>40 %>
        <%= cook.content[0..39]+' ...' %>
      <% else %>
        <%= cook.content %>
      <% end %>
    </td>
    <td><%= cook.remark %></td>
    <td><%= cook.updated_at %></td>
    <td><%= link_to '详细', cook %></td>
    <td><%= link_to '编辑', edit_cook_path(cook) %></td>
    <td><%= link_to "删除", :controller => "cooks", :action => "delete", :id => cook %>
  </tr>
<% end %>
</table>

<br />

app/views/cooks/new.html.erb
<h1>New cook</h1>

<%= render 'form' %>

<%= link_to 'Back', cooks_path %>

app/views/cooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @cook.content %>
</p>

<p>
  <b>Owner:</b>
  <%= @cook.owner %>
</p>

<p>
  <b>Username:</b>
  <%= @cook.username %>
</p>

<p>
  <b>Password:</b>
  <%= @cook.passwd %>
</p>

<p>
  <b>Page type:</b>
  <%= @cook.page_type %>
</p>

<p>
  <b>是否过期:</b>
  <%= @cook.expired %>
</p>

<p>
  <b>是否访问频繁:</b>
  <%= @cook.frequent %>
</p>

<p>
  <b>备注:</b>
  <%= @cook.remark %>
</p>


<%= link_to 'Edit', edit_cook_path(@cook) %> |
<%= link_to 'Back', cooks_path %>